In [1]:
import numpy as np

# 模拟一个 5x5 的灰度图像矩阵
mock_image = np.array([
    [10, 10, 20, 20, 20],
    [10, 150, 150, 150, 20],
    [10, 150, 200, 150, 20],
    [10, 150, 150, 150, 20],
    [20, 20, 20, 20, 20]
], dtype=np.uint8)

# 手动实现 3x3 均值滤波
def blur(image, kernel_size):
    h, w = image.shape
    k = kernel_size // 2
    result = np.zeros_like(image)
    for i in range(k, h - k):
        for j in range(k, w - k):
            result[i, j] = np.mean(image[i-k:i+k+1, j-k:j+k+1])
    return result

blurred = blur(mock_image, 3)

print("--- 原始滤波前的图像矩阵 ---")
print(mock_image)
print("\n--- 均值滤波后的图像矩阵 ---")
print(blurred)

--- 原始滤波前的图像矩阵 ---
[[ 10  10  20  20  20]
 [ 10 150 150 150  20]
 [ 10 150 200 150  20]
 [ 10 150 150 150  20]
 [ 20  20  20  20  20]]

--- 均值滤波后的图像矩阵 ---
[[  0   0   0   0   0]
 [  0  78 111  83   0]
 [  0 108 155 112   0]
 [  0  81 112  83   0]
 [  0   0   0   0   0]]
